modLoader = "javafml"
loaderVersion = "[36,)"
license = "Unlicense"
issueTrackerURL = "https://github.com/pixiemc/loader/issues"

[[mods]]
modId = "pixie_loader"
version = "0.0.1"
displayName = "Pixie Loader"
displayURL = "https://pixie.rip/"
description = '''A mod to load Pixie into Essential Mod for scenarios where you don't want to, or can't, set the environment variable.'''
